//! Zero-knowledge eVRF proof system per Section 4 of the Golden paper.
//!
//! Implements the exponent Verifiable Random Function (eVRF) from Section 4 of
//! the Golden paper (Bünz, Choi, Komlo,
//! [IACR 2025/1924](https://eprint.iacr.org/2025/1924)).
//!
//! The eVRF proves the `R_eVRF` relation (Figure 3): the prover demonstrates
//! that an encryption pad `r` was correctly derived from a Diffie-Hellman shared
//! secret without revealing the secret key `sk`. The relation captures:
//!
//! 1. `PK_1 = g^{sk_1}` (public key ownership)
//! 2. `S = PK_2^{sk_1}` (DH shared secret)
//! 3. `r = beta * (H_1(msg)^k).X + (H_2(msg)^k).X` (pad derivation via leftover hash lemma)
//! 4. `R = g^r` (pad commitment)
//!
//! The circuit is encoded as R1CS constraints and proved using
//! [ark-spartan](https://github.com/arkworks-rs/spartan)'s NIZK system
//! (Bulletproofs-style IPA reduction).
//!
//! # Batch Optimization (Section 5.3/4.6)
//!
//! For `n-1` eVRF evaluations sharing the same prover key `sk_1`, the
//! bit-decomposition of `sk_1` is shared across all statements. This reduces
//! per-statement constraint count from `14*lambda + 14` to approximately
//! `10*lambda + 10` (~29% reduction) and keeps proof size logarithmic.
//!
//! # Submodules
//!
//! - [`circuit`] -- R1CS circuit definitions for single and batch eVRF
//! - [`adapter`] -- ark-relations to ark-spartan bridge
//! - [`bit_decompose`] -- bit decomposition gadget (`lambda + 2` constraints)
//! - [`exponentiation`] -- elliptic curve exponentiation gadget (`3*lambda + 2` constraints)
//! - [`nonnative`] -- non-native field arithmetic for cross-field operations

pub mod adapter;
pub mod bit_decompose;
pub mod circuit;
pub mod exponentiation;
pub mod nonnative;

use ark_bls12_381::{Fr, G1Affine, G1Projective};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
#[cfg(feature = "borsh")]
use borsh::{BorshDeserialize, BorshSerialize};
#[cfg(feature = "borsh")]
use std::io::{self, Read, Write};

use self::adapter::capture_circuit;
use self::circuit::{BatchEVRFCircuit, EVRFCircuit};
use crate::types::NodeId;
use libspartan::{NIZKGens, NIZK};

/// An eVRF proof using ark-spartan's NIZK proof system.
///
/// Per Golden paper Section 3.4: "We use Bulletproofs \[15\] to prove R1CS satisfiability."
/// The proof is generated by ark-spartan's NIZK system which provides a production-quality
/// R1CS-to-IPA reduction with correct public-input binding.
///
/// The proof is self-describing: it carries the R1CS dimensions needed for
/// verification so the verifier can reconstruct the generators independently.
/// Proof size scales logarithmically with the number of constraints (~1.5 KB
/// for a single statement, ~2.2 KB for 99 batched statements).
#[derive(Clone, Debug)]
pub struct EVRFProof {
    /// Serialized ark-spartan NIZK proof bytes (compressed via [`CanonicalSerialize`]).
    pub proof_bytes: Vec<u8>,
    /// Number of R1CS constraints in the circuit.
    ///
    /// For a single eVRF statement: `14 * lambda + 14 = 3598` (lambda = 256).
    /// For a batch of `m` statements: approximately `4*lambda + 4 + m*(10*lambda + 10)`.
    pub num_constraints: usize,
    /// Number of witness (private) variables in the R1CS instance.
    pub num_vars: usize,
    /// Number of public input variables in the R1CS instance.
    pub num_inputs: usize,
    /// Whether this is a batch proof covering multiple eVRF evaluations (Section 5.3).
    ///
    /// Batch proofs must be verified with [`verify_evrf_batch`], not [`verify_evrf`].
    pub is_batch: bool,
}

#[cfg(feature = "borsh")]
impl BorshSerialize for EVRFProof {
    fn serialize<W: Write>(&self, writer: &mut W) -> io::Result<()> {
        BorshSerialize::serialize(&(self.num_constraints as u32), writer)?;
        BorshSerialize::serialize(&(self.num_vars as u32), writer)?;
        BorshSerialize::serialize(&(self.num_inputs as u32), writer)?;
        BorshSerialize::serialize(&self.is_batch, writer)?;
        BorshSerialize::serialize(&self.proof_bytes, writer)?;
        Ok(())
    }
}

#[cfg(feature = "borsh")]
impl BorshDeserialize for EVRFProof {
    fn deserialize_reader<R: Read>(reader: &mut R) -> io::Result<Self> {
        let num_constraints = u32::deserialize_reader(reader)? as usize;
        let num_vars = u32::deserialize_reader(reader)? as usize;
        let num_inputs = u32::deserialize_reader(reader)? as usize;
        let is_batch: bool = BorshDeserialize::deserialize_reader(reader)?;
        let proof_bytes: Vec<u8> = BorshDeserialize::deserialize_reader(reader)?;
        Ok(EVRFProof {
            proof_bytes,
            num_constraints,
            num_vars,
            num_inputs,
            is_batch,
        })
    }
}

/// Generate an eVRF proof for a single statement using ark-spartan NIZK.
///
/// Per Golden paper Section 4.2 (eVRF Evaluate): produces a ZK proof `pi`
/// for the `R_eVRF` relation (Figure 3) that the eVRF pad was correctly derived.
///
/// # Parameters
///
/// - `sk1` -- the prover's secret key
/// - `pk1` -- the prover's public key (`g^{sk1}`)
/// - `pk2` -- the peer's public key (DH counterparty)
/// - `r_value` -- the eVRF pad value `r`
/// - `r_commitment` -- the pad commitment `R = g^r`
/// - `beta` -- public leftover hash lemma parameter
///
/// # Errors
///
/// Returns an error string if R1CS synthesis or proof generation fails.
pub fn prove_evrf(
    sk1: Fr,
    pk1: G1Affine,
    pk2: G1Affine,
    r_value: Fr,
    r_commitment: G1Affine,
    beta: Fr,
) -> Result<EVRFProof, String> {
    let circuit = EVRFCircuit::new(sk1, pk1, pk2, r_value, r_commitment, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    let mut transcript = merlin::Transcript::new(b"golden-evrf-proof");
    let proof = NIZK::prove(
        &spartan_data.instance,
        spartan_data.vars,
        &spartan_data.inputs,
        &gens,
        &mut transcript,
    );

    // Serialize the proof
    let mut proof_bytes = Vec::new();
    proof
        .serialize_compressed(&mut proof_bytes)
        .map_err(|e| format!("Failed to serialize proof: {}", e))?;

    Ok(EVRFProof {
        proof_bytes,
        num_constraints: spartan_data.num_cons,
        num_vars: spartan_data.num_vars,
        num_inputs: spartan_data.num_inputs,
        is_batch: false,
    })
}

/// Generate a batched eVRF proof for all peers using ark-spartan NIZK.
///
/// Per Golden paper Section 5.3/4.6: one proof covers all `n-1` eVRF evaluations
/// by sharing the `sk_1` bit-decomposition gadget across all statements. This is
/// the recommended mode for DKG with more than 2 participants.
///
/// # Parameters
///
/// - `sk1` -- the prover's secret key
/// - `my_pk` -- the prover's public key (`g^{sk1}`)
/// - `peers` -- list of `(peer_id, peer_pk)` for all other participants
/// - `pads` -- list of `(peer_id, r_value, r_commitment)` for each peer
/// - `beta` -- public leftover hash lemma parameter
///
/// # Errors
///
/// Returns an error string if R1CS synthesis or proof generation fails.
pub fn prove_evrf_batch(
    sk1: Fr,
    my_pk: G1Affine,
    peers: &[(NodeId, G1Affine)],
    pads: &[(NodeId, Fr, G1Affine)],
    beta: Fr,
) -> Result<EVRFProof, String> {
    let circuit = BatchEVRFCircuit::new(sk1, my_pk, peers, pads, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    let mut transcript = merlin::Transcript::new(b"golden-evrf-batch-proof");
    let proof = NIZK::prove(
        &spartan_data.instance,
        spartan_data.vars,
        &spartan_data.inputs,
        &gens,
        &mut transcript,
    );

    let mut proof_bytes = Vec::new();
    proof
        .serialize_compressed(&mut proof_bytes)
        .map_err(|e| format!("Failed to serialize proof: {}", e))?;

    Ok(EVRFProof {
        proof_bytes,
        num_constraints: spartan_data.num_cons,
        num_vars: spartan_data.num_vars,
        num_inputs: spartan_data.num_inputs,
        is_batch: true,
    })
}

/// Verify a single-statement eVRF proof using ark-spartan NIZK.
///
/// Per Golden paper Section 4.2 (eVRF Verify): verifies the proof `pi`
/// against the public inputs `(PK_1, PK_2, R, beta)`. The verifier re-synthesizes
/// the `R_eVRF` circuit with the claimed public inputs to reconstruct the R1CS
/// instance, then checks the proof against it. This binds the proof to the
/// specific public inputs -- a proof for different inputs will be rejected.
///
/// # Parameters
///
/// - `pk1` -- the prover's public key
/// - `pk2` -- the peer's public key (DH counterparty)
/// - `r_commitment` -- the claimed pad commitment `R = g^r`
/// - `beta` -- public leftover hash lemma parameter
/// - `proof` -- the [`EVRFProof`] to verify (must have `is_batch == false`)
///
/// # Returns
///
/// `Ok(true)` if the proof verifies, `Ok(false)` if verification fails,
/// or `Err` if deserialization or circuit synthesis fails.
///
/// # Errors
///
/// Returns `Err` with a description if the proof is a batch proof (use
/// [`verify_evrf_batch`] instead) or if deserialization fails.
pub fn verify_evrf(
    pk1: G1Affine,
    pk2: G1Affine,
    r_commitment: G1Affine,
    beta: Fr,
    proof: &EVRFProof,
) -> Result<bool, String> {
    if proof.is_batch {
        return Err("Use verify_evrf_batch for batch proofs".to_string());
    }

    // 1. Re-synthesize the circuit with the verifier's public inputs
    let circuit = EVRFCircuit::for_verification(pk1, pk2, r_commitment, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    // 2. Reconstruct generators
    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    // 3. Deserialize the proof
    let nizk_proof = NIZK::<G1Projective>::deserialize_compressed(&proof.proof_bytes[..])
        .map_err(|e| format!("Failed to deserialize proof: {}", e))?;

    // 4. Verify with the verifier's public inputs
    let mut transcript = merlin::Transcript::new(b"golden-evrf-proof");
    match nizk_proof.verify(
        &spartan_data.instance,
        &spartan_data.inputs,
        &mut transcript,
        &gens,
    ) {
        Ok(()) => Ok(true),
        Err(_) => Ok(false),
    }
}

/// Verify a batched eVRF proof using ark-spartan NIZK with full public-input binding.
///
/// Per Golden paper Section 5.3: the batch proof covers all `n-1` eVRF evaluations.
/// The verifier re-synthesizes the `BatchEVRFCircuit` with the claimed public inputs
/// (`pk1`, all peer PKs, all `R` commitments, `beta`) to reconstruct the R1CS
/// instance, then checks the proof against it.
///
/// # Parameters
///
/// - `pk1` -- the prover's public key
/// - `peers` -- list of `(peer_id, peer_pk)` for all other participants
/// - `pad_commitments` -- list of `(peer_id, R_commitment)` for each peer
/// - `beta` -- public leftover hash lemma parameter
/// - `proof` -- the [`EVRFProof`] to verify (should have `is_batch == true`)
///
/// # Returns
///
/// `Ok(true)` if the proof verifies, `Ok(false)` if verification fails,
/// or `Err` if deserialization or circuit synthesis fails.
pub fn verify_evrf_batch(
    pk1: G1Affine,
    peers: &[(NodeId, G1Affine)],
    pad_commitments: &[(NodeId, G1Affine)],
    beta: Fr,
    proof: &EVRFProof,
) -> Result<bool, String> {
    // Re-synthesize the batch circuit with the verifier's public inputs
    let circuit = BatchEVRFCircuit::for_verification(pk1, peers, pad_commitments, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    // Reconstruct generators
    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    // Deserialize the proof
    let nizk_proof = NIZK::<G1Projective>::deserialize_compressed(&proof.proof_bytes[..])
        .map_err(|e| format!("Failed to deserialize batch proof: {}", e))?;

    // Verify with the verifier's public inputs
    let mut transcript = merlin::Transcript::new(b"golden-evrf-batch-proof");
    match nizk_proof.verify(
        &spartan_data.instance,
        &spartan_data.inputs,
        &mut transcript,
        &gens,
    ) {
        Ok(()) => Ok(true),
        Err(_) => Ok(false),
    }
}

#[cfg(test)]
mod verification_tests {
    use super::*;
    use ark_ec::{AffineRepr, CurveGroup};
    use ark_ff::UniformRand;

    #[test]
    fn test_verify_evrf_valid_proof() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let sk2 = Fr::rand(&mut rng);
        let pk2 = (G1Affine::generator() * sk2).into_affine();
        let r_value = Fr::rand(&mut rng);
        let r_commitment = (G1Affine::generator() * r_value).into_affine();
        let beta = Fr::rand(&mut rng);

        let proof = prove_evrf(sk1, pk1, pk2, r_value, r_commitment, beta).unwrap();
        let result = verify_evrf(pk1, pk2, r_commitment, beta, &proof).unwrap();
        assert!(result, "Valid proof should verify");
    }

    #[test]
    fn test_verify_evrf_wrong_public_inputs() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let sk2 = Fr::rand(&mut rng);
        let pk2 = (G1Affine::generator() * sk2).into_affine();
        let r_value = Fr::rand(&mut rng);
        let r_commitment = (G1Affine::generator() * r_value).into_affine();
        let beta = Fr::rand(&mut rng);

        let proof = prove_evrf(sk1, pk1, pk2, r_value, r_commitment, beta).unwrap();

        // Verify with WRONG pk2 -- should fail
        let wrong_pk2 = (G1Affine::generator() * Fr::rand(&mut rng)).into_affine();
        let result = verify_evrf(pk1, wrong_pk2, r_commitment, beta, &proof).unwrap();
        assert!(
            !result,
            "Proof verified against wrong public inputs should fail"
        );
    }

    #[test]
    fn test_verify_evrf_batch_valid() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let beta = Fr::rand(&mut rng);

        // Create 3 peers
        let mut peers = Vec::new();
        let mut pads = Vec::new();
        let mut pad_commitments = Vec::new();
        for peer_id in 2..=4u32 {
            let sk_peer = Fr::rand(&mut rng);
            let pk_peer = (G1Affine::generator() * sk_peer).into_affine();
            let r_value = Fr::rand(&mut rng);
            let r_commitment = (G1Affine::generator() * r_value).into_affine();
            peers.push((peer_id, pk_peer));
            pads.push((peer_id, r_value, r_commitment));
            pad_commitments.push((peer_id, r_commitment));
        }

        let proof = prove_evrf_batch(sk1, pk1, &peers, &pads, beta).unwrap();

        // Verify with correct public inputs
        let result = verify_evrf_batch(pk1, &peers, &pad_commitments, beta, &proof).unwrap();
        assert!(result, "Valid batch proof should verify");
    }

    #[test]
    fn test_verify_evrf_batch_wrong_peer() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let beta = Fr::rand(&mut rng);

        let mut peers = Vec::new();
        let mut pads = Vec::new();
        let mut pad_commitments = Vec::new();
        for peer_id in 2..=4u32 {
            let sk_peer = Fr::rand(&mut rng);
            let pk_peer = (G1Affine::generator() * sk_peer).into_affine();
            let r_value = Fr::rand(&mut rng);
            let r_commitment = (G1Affine::generator() * r_value).into_affine();
            peers.push((peer_id, pk_peer));
            pads.push((peer_id, r_value, r_commitment));
            pad_commitments.push((peer_id, r_commitment));
        }

        let proof = prove_evrf_batch(sk1, pk1, &peers, &pads, beta).unwrap();

        // Verify with WRONG peer PK -- should fail
        let mut wrong_peers = peers.clone();
        wrong_peers[1].1 = (G1Affine::generator() * Fr::rand(&mut rng)).into_affine();
        let result = verify_evrf_batch(pk1, &wrong_peers, &pad_commitments, beta, &proof).unwrap();
        assert!(!result, "Batch proof with wrong peer PK should fail");
    }

    #[test]
    fn test_verify_evrf_wrong_beta() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let sk2 = Fr::rand(&mut rng);
        let pk2 = (G1Affine::generator() * sk2).into_affine();
        let r_value = Fr::rand(&mut rng);
        let r_commitment = (G1Affine::generator() * r_value).into_affine();
        let beta = Fr::rand(&mut rng);

        let proof = prove_evrf(sk1, pk1, pk2, r_value, r_commitment, beta).unwrap();

        // Verify with WRONG beta -- should fail
        let wrong_beta = Fr::rand(&mut rng);
        let result = verify_evrf(pk1, pk2, r_commitment, wrong_beta, &proof).unwrap();
        assert!(!result, "Proof verified against wrong beta should fail");
    }
}
