module Golden_rs.Zk_evrf
#set-options "--fuel 0 --ifuel 1 --z3rlimit 15"
open FStar.Mul
open Core_models

let _ =
  (* This module has implicit dependencies, here we make them explicit. *)
  (* The implicit dependencies arise from typeclasses instances. *)
  let open Ark_bls12_381_.Curves.G1 in
  let open Ark_ec in
  let open Ark_ec.Models.Short_weierstrass in
  let open Ark_ec.Models.Short_weierstrass.Group in
  let open Ark_relations.R1cs.Constraint_system in
  let open Ark_serialize in
  let open Ark_serialize.Error in
  let open Borsh.De in
  let open Borsh.Ser in
  let open Golden_rs.Zk_evrf.Circuit in
  let open Libspartan in
  let open Std.Io in
  let open Std.Io.Impls in
  ()

/// An eVRF proof using ark-spartan's NIZK proof system.
/// Per Golden paper Section 3.4: "We use Bulletproofs [15] to prove R1CS satisfiability."
/// The proof is generated by ark-spartan's NIZK system which provides a production-quality
/// R1CS-to-IPA reduction with correct public-input binding.
type t_EVRFProof = {
  f_proof_bytes:Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global;
  f_num_constraints:usize;
  f_num_vars:usize;
  f_num_inputs:usize;
  f_is_batch:bool
}

let impl_2: Core_models.Clone.t_Clone t_EVRFProof =
  { f_clone = (fun x -> x); f_clone_pre = (fun _ -> True); f_clone_post = (fun _ _ -> True) }

[@@ FStar.Tactics.Typeclasses.tcinstance]
assume
val impl_3': Core_models.Fmt.t_Debug t_EVRFProof

unfold
let impl_3 = impl_3'

[@@ FStar.Tactics.Typeclasses.tcinstance]
let impl: Borsh.Ser.t_BorshSerialize t_EVRFProof =
  {
    f_serialize_pre
    =
    (fun
        (#v_W: Type0)
        (#[FStar.Tactics.Typeclasses.tcresolve ()] i0: Std.Io.t_Write v_W)
        (self: t_EVRFProof)
        (writer: v_W)
        ->
        true);
    f_serialize_post
    =
    (fun
        (#v_W: Type0)
        (#[FStar.Tactics.Typeclasses.tcresolve ()] i0: Std.Io.t_Write v_W)
        (self: t_EVRFProof)
        (writer: v_W)
        (out1: (v_W & Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error))
        ->
        true);
    f_serialize
    =
    fun
      (#v_W: Type0)
      (#[FStar.Tactics.Typeclasses.tcresolve ()] i0: Std.Io.t_Write v_W)
      (self: t_EVRFProof)
      (writer: v_W)
      ->
      let (tmp0: v_W), (out: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error) =
        Borsh.Ser.f_serialize #u32
          #FStar.Tactics.Typeclasses.solve
          #v_W
          (cast (self.f_num_constraints <: usize) <: u32)
          writer
      in
      let writer:v_W = tmp0 in
      match out <: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error with
      | Core_models.Result.Result_Ok _ ->
        let (tmp0: v_W), (out: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error) =
          Borsh.Ser.f_serialize #u32
            #FStar.Tactics.Typeclasses.solve
            #v_W
            (cast (self.f_num_vars <: usize) <: u32)
            writer
        in
        let writer:v_W = tmp0 in
        (match out <: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error with
          | Core_models.Result.Result_Ok _ ->
            let (tmp0: v_W), (out: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error) =
              Borsh.Ser.f_serialize #u32
                #FStar.Tactics.Typeclasses.solve
                #v_W
                (cast (self.f_num_inputs <: usize) <: u32)
                writer
            in
            let writer:v_W = tmp0 in
            (match out <: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error with
              | Core_models.Result.Result_Ok _ ->
                let (tmp0: v_W), (out: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
                =
                  Borsh.Ser.f_serialize #bool
                    #FStar.Tactics.Typeclasses.solve
                    #v_W
                    self.f_is_batch
                    writer
                in
                let writer:v_W = tmp0 in
                (match out <: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error with
                  | Core_models.Result.Result_Ok _ ->
                    let
                    (tmp0: v_W), (out: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
                    =
                      Borsh.Ser.f_serialize #(Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global)
                        #FStar.Tactics.Typeclasses.solve
                        #v_W
                        self.f_proof_bytes
                        writer
                    in
                    let writer:v_W = tmp0 in
                    (match out <: Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error with
                      | Core_models.Result.Result_Ok _ ->
                        let hax_temp_output:Core_models.Result.t_Result Prims.unit
                          Std.Io.Error.t_Error =
                          Core_models.Result.Result_Ok (() <: Prims.unit)
                          <:
                          Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error
                        in
                        writer, hax_temp_output
                        <:
                        (v_W & Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
                      | Core_models.Result.Result_Err err ->
                        writer,
                        (Core_models.Result.Result_Err err
                          <:
                          Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
                        <:
                        (v_W & Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error))
                  | Core_models.Result.Result_Err err ->
                    writer,
                    (Core_models.Result.Result_Err err
                      <:
                      Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
                    <:
                    (v_W & Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error))
              | Core_models.Result.Result_Err err ->
                writer,
                (Core_models.Result.Result_Err err
                  <:
                  Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
                <:
                (v_W & Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error))
          | Core_models.Result.Result_Err err ->
            writer,
            (Core_models.Result.Result_Err err
              <:
              Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
            <:
            (v_W & Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error))
      | Core_models.Result.Result_Err err ->
        writer,
        (Core_models.Result.Result_Err err
          <:
          Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
        <:
        (v_W & Core_models.Result.t_Result Prims.unit Std.Io.Error.t_Error)
  }

[@@ FStar.Tactics.Typeclasses.tcinstance]
let impl_1: Borsh.De.t_BorshDeserialize t_EVRFProof =
  {
    f_deserialize_reader_pre
    =
    (fun
        (#v_R: Type0)
        (#[FStar.Tactics.Typeclasses.tcresolve ()] i0: Std.Io.t_Read v_R)
        (reader: v_R)
        ->
        true);
    f_deserialize_reader_post
    =
    (fun
        (#v_R: Type0)
        (#[FStar.Tactics.Typeclasses.tcresolve ()] i0: Std.Io.t_Read v_R)
        (reader: v_R)
        (out1: (v_R & Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error))
        ->
        true);
    f_deserialize_reader
    =
    fun
      (#v_R: Type0)
      (#[FStar.Tactics.Typeclasses.tcresolve ()] i0: Std.Io.t_Read v_R)
      (reader: v_R)
      ->
      let (tmp0: v_R), (out: Core_models.Result.t_Result u32 Std.Io.Error.t_Error) =
        Borsh.De.f_deserialize_reader #u32 #FStar.Tactics.Typeclasses.solve #v_R reader
      in
      let reader:v_R = tmp0 in
      match out <: Core_models.Result.t_Result u32 Std.Io.Error.t_Error with
      | Core_models.Result.Result_Ok hoist74 ->
        let num_constraints:usize = cast (hoist74 <: u32) <: usize in
        let (tmp0: v_R), (out: Core_models.Result.t_Result u32 Std.Io.Error.t_Error) =
          Borsh.De.f_deserialize_reader #u32 #FStar.Tactics.Typeclasses.solve #v_R reader
        in
        let reader:v_R = tmp0 in
        (match out <: Core_models.Result.t_Result u32 Std.Io.Error.t_Error with
          | Core_models.Result.Result_Ok hoist76 ->
            let num_vars:usize = cast (hoist76 <: u32) <: usize in
            let (tmp0: v_R), (out: Core_models.Result.t_Result u32 Std.Io.Error.t_Error) =
              Borsh.De.f_deserialize_reader #u32 #FStar.Tactics.Typeclasses.solve #v_R reader
            in
            let reader:v_R = tmp0 in
            (match out <: Core_models.Result.t_Result u32 Std.Io.Error.t_Error with
              | Core_models.Result.Result_Ok hoist78 ->
                let num_inputs:usize = cast (hoist78 <: u32) <: usize in
                let (tmp0: v_R), (out: Core_models.Result.t_Result bool Std.Io.Error.t_Error) =
                  Borsh.De.f_deserialize_reader #bool #FStar.Tactics.Typeclasses.solve #v_R reader
                in
                let reader:v_R = tmp0 in
                (match out <: Core_models.Result.t_Result bool Std.Io.Error.t_Error with
                  | Core_models.Result.Result_Ok (is_batch: bool) ->
                    let
                    (tmp0: v_R),
                    (out:
                      Core_models.Result.t_Result (Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global)
                        Std.Io.Error.t_Error) =
                      Borsh.De.f_deserialize_reader #(Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global)
                        #FStar.Tactics.Typeclasses.solve
                        #v_R
                        reader
                    in
                    let reader:v_R = tmp0 in
                    (match
                        out
                        <:
                        Core_models.Result.t_Result (Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global)
                          Std.Io.Error.t_Error
                      with
                      | Core_models.Result.Result_Ok
                        (proof_bytes: Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global) ->
                        let hax_temp_output:Core_models.Result.t_Result t_EVRFProof
                          Std.Io.Error.t_Error =
                          Core_models.Result.Result_Ok
                          ({
                              f_proof_bytes = proof_bytes;
                              f_num_constraints = num_constraints;
                              f_num_vars = num_vars;
                              f_num_inputs = num_inputs;
                              f_is_batch = is_batch
                            }
                            <:
                            t_EVRFProof)
                          <:
                          Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error
                        in
                        reader, hax_temp_output
                        <:
                        (v_R & Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error)
                      | Core_models.Result.Result_Err err ->
                        reader,
                        (Core_models.Result.Result_Err err
                          <:
                          Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error)
                        <:
                        (v_R & Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error))
                  | Core_models.Result.Result_Err err ->
                    reader,
                    (Core_models.Result.Result_Err err
                      <:
                      Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error)
                    <:
                    (v_R & Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error))
              | Core_models.Result.Result_Err err ->
                reader,
                (Core_models.Result.Result_Err err
                  <:
                  Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error)
                <:
                (v_R & Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error))
          | Core_models.Result.Result_Err err ->
            reader,
            (Core_models.Result.Result_Err err
              <:
              Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error)
            <:
            (v_R & Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error))
      | Core_models.Result.Result_Err err ->
        reader,
        (Core_models.Result.Result_Err err
          <:
          Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error)
        <:
        (v_R & Core_models.Result.t_Result t_EVRFProof Std.Io.Error.t_Error)
  }

/// Generate an eVRF proof for a single statement using ark-spartan NIZK.
/// Per Golden paper Section 4.2 (eVRF Evaluate): produces a ZK proof `pi`
/// for the R_eVRF relation (Figure 3) that the eVRF pad was correctly derived.

(* prove_evrf, prove_evrf_batch, verify_evrf, verify_evrf_batch:
   replaced with assume val. These orchestrate the ZK proving pipeline
   (adapter -> spartan -> serialize) which is verified by Kani harnesses. *)

assume val prove_evrf
      (sk1:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (pk1 pk2: Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (r_value:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (r_commitment:
          Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
    : Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String

assume val prove_evrf_batch
      (sk1:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (my_pk: Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (peers:
          t_Slice
          (u32 & Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config))
      (pads:
          t_Slice
          (u32 &
            Ark_ff.Fields.Models.Fp.t_Fp
              (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                  Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4) &
            Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config))
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
    : Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String

assume val verify_evrf
      (pk1 pk2 r_commitment:
          Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (proof: t_EVRFProof)
    : Core_models.Result.t_Result bool Alloc.String.t_String

assume val verify_evrf_batch
      (pk1: Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (peers pad_commitments:
          t_Slice
          (u32 & Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config))
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (proof: t_EVRFProof)
    : Core_models.Result.t_Result bool Alloc.String.t_String
