module Golden_dkg.Zk_evrf
#set-options "--fuel 0 --ifuel 1 --z3rlimit 15"
open FStar.Mul
open Core_models

let _ =
  (* This module has implicit dependencies, here we make them explicit. *)
  (* The implicit dependencies arise from typeclasses instances. *)
  let open Ark_bls12_381_.Curves.G1 in
  let open Ark_ec in
  let open Ark_ec.Models.Short_weierstrass in
  let open Ark_ec.Models.Short_weierstrass.Group in
  let open Ark_relations.R1cs.Constraint_system in
  let open Ark_serialize in
  let open Ark_serialize.Error in
  let open Golden_dkg.Zk_evrf.Circuit in
  let open Libspartan in
  let open Std.Io in
  let open Std.Io.Impls in
  ()

/// An eVRF proof using ark-spartan's NIZK proof system.
/// Per Golden paper Section 3.4: "We use Bulletproofs \[15\] to prove R1CS satisfiability."
/// The proof is generated by ark-spartan's NIZK system which provides a production-quality
/// R1CS-to-IPA reduction with correct public-input binding.
/// The proof is self-describing: it carries the R1CS dimensions needed for
/// verification so the verifier can reconstruct the generators independently.
/// Proof size scales logarithmically with the number of constraints (~1.5 KB
/// for a single statement, ~2.2 KB for 99 batched statements).
type t_EVRFProof = {
  f_proof_bytes:Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global;
  f_num_constraints:usize;
  f_num_vars:usize;
  f_num_inputs:usize;
  f_is_batch:bool
}

let impl: Core_models.Clone.t_Clone t_EVRFProof =
  { f_clone = (fun x -> x); f_clone_pre = (fun _ -> True); f_clone_post = (fun _ _ -> True) }

[@@ FStar.Tactics.Typeclasses.tcinstance]
assume
val impl_1': Core_models.Fmt.t_Debug t_EVRFProof

unfold
let impl_1 = impl_1'

/// Generate an eVRF proof for a single statement using ark-spartan NIZK.
/// Per Golden paper Section 4.2 (eVRF Evaluate): produces a ZK proof `pi`
/// for the `R_eVRF` relation (Figure 3) that the eVRF pad was correctly derived.
/// # Parameters
/// - `sk1` -- the prover's secret key
/// - `pk1` -- the prover's public key (`g^{sk1}`)
/// - `pk2` -- the peer's public key (DH counterparty)
/// - `r_value` -- the eVRF pad value `r`
/// - `r_commitment` -- the pad commitment `R = g^r`
/// - `beta` -- public leftover hash lemma parameter
/// # Errors
/// Returns an error string if R1CS synthesis or proof generation fails.
let prove_evrf
      (sk1:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (pk1 pk2: Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (r_value:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (r_commitment:
          Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
    : Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String =
  let circuit:Golden_dkg.Zk_evrf.Circuit.t_EVRFCircuit =
    Golden_dkg.Zk_evrf.Circuit.impl_EVRFCircuit__new sk1 pk1 pk2 r_value r_commitment beta
  in
  match
    Golden_dkg.Zk_evrf.Adapter.capture_circuit #Golden_dkg.Zk_evrf.Circuit.t_EVRFCircuit circuit
    <:
    Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_CapturedR1CS Alloc.String.t_String
  with
  | Core_models.Result.Result_Ok captured ->
    (match
        Golden_dkg.Zk_evrf.Adapter.to_spartan captured
        <:
        Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_SpartanData Alloc.String.t_String
      with
      | Core_models.Result.Result_Ok spartan_data ->
        let gens:Libspartan.t_NIZKGens
        (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config) =
          Libspartan.impl_4__new #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
              Ark_bls12_381_.Curves.G1.t_Config)
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_cons
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_vars
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_inputs
        in
        let transcript:Merlin.Transcript.t_Transcript =
          Merlin.Transcript.impl_Transcript__new ((let list =
                  [
                    mk_u8 103; mk_u8 111; mk_u8 108; mk_u8 100; mk_u8 101; mk_u8 110; mk_u8 45;
                    mk_u8 101; mk_u8 118; mk_u8 114; mk_u8 102; mk_u8 45; mk_u8 112; mk_u8 114;
                    mk_u8 111; mk_u8 111; mk_u8 102
                  ]
                in
                FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 17);
                Rust_primitives.Hax.array_of_list 17 list)
              <:
              t_Slice u8)
        in
        let
        (tmp0: Merlin.Transcript.t_Transcript),
        (out:
          Libspartan.t_NIZK
          (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config)) =
          Libspartan.impl_5__prove #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
              Ark_bls12_381_.Curves.G1.t_Config)
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_instance
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_vars
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_inputs
            gens
            transcript
        in
        let transcript:Merlin.Transcript.t_Transcript = tmp0 in
        let proof:Libspartan.t_NIZK
        (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config) =
          out
        in
        let proof_bytes:Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global = Alloc.Vec.impl__new #u8 () in
        (match
            Core_models.Result.impl__map_err #Prims.unit
              #Ark_serialize.Error.t_SerializationError
              #Alloc.String.t_String
              #(Ark_serialize.Error.t_SerializationError -> Alloc.String.t_String)
              (Rust_primitives.Hax.failure "The mutation of this &mut is not allowed here.\n\nThis is discussed in issue https://github.com/hacspec/hax/issues/420.\nPlease upvote or comment this issue if you see this error message.\nNote: the error was labeled with context `DirectAndMut`.\n"
                  "ark_serialize::f_serialize_compressed::<\n &mut alloc::vec::t_Vec<int, alloc::alloc::t_Global>,\n >(&(proof), &mut (proof_bytes))"

                <:
                Core_models.Result.t_Result Prims.unit Ark_serialize.Error.t_SerializationError)
              (fun e ->
                  let e:Ark_serialize.Error.t_SerializationError = e in
                  let args:Ark_serialize.Error.t_SerializationError =
                    e <: Ark_serialize.Error.t_SerializationError
                  in
                  let args:t_Array Core_models.Fmt.Rt.t_Argument (mk_usize 1) =
                    let list =
                      [
                        Core_models.Fmt.Rt.impl__new_display #Ark_serialize.Error.t_SerializationError
                          args
                      ]
                    in
                    FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                    Rust_primitives.Hax.array_of_list 1 list
                  in
                  Core_models.Hint.must_use #Alloc.String.t_String
                    (Alloc.Fmt.format (Core_models.Fmt.Rt.impl_1__new_v1 (mk_usize 1)
                            (mk_usize 1)
                            (let list = ["Failed to serialize proof: "] in
                              FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                              Rust_primitives.Hax.array_of_list 1 list)
                            args
                          <:
                          Core_models.Fmt.t_Arguments)
                      <:
                      Alloc.String.t_String))
            <:
            Core_models.Result.t_Result Prims.unit Alloc.String.t_String
          with
          | Core_models.Result.Result_Ok _ ->
            Core_models.Result.Result_Ok
            ({
                f_proof_bytes = proof_bytes;
                f_num_constraints = spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_cons;
                f_num_vars = spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_vars;
                f_num_inputs = spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_inputs;
                f_is_batch = false
              }
              <:
              t_EVRFProof)
            <:
            Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String
          | Core_models.Result.Result_Err err ->
            Core_models.Result.Result_Err err
            <:
            Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String)
      | Core_models.Result.Result_Err err ->
        Core_models.Result.Result_Err err
        <:
        Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String)
  | Core_models.Result.Result_Err err ->
    Core_models.Result.Result_Err err
    <:
    Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String

/// Generate a batched eVRF proof for all peers using ark-spartan NIZK.
/// Per Golden paper Section 5.3/4.6: one proof covers all `n-1` eVRF evaluations
/// by sharing the `sk_1` bit-decomposition gadget across all statements. This is
/// the recommended mode for DKG with more than 2 participants.
/// # Parameters
/// - `sk1` -- the prover's secret key
/// - `my_pk` -- the prover's public key (`g^{sk1}`)
/// - `peers` -- list of `(peer_id, peer_pk)` for all other participants
/// - `pads` -- list of `(peer_id, r_value, r_commitment)` for each peer
/// - `beta` -- public leftover hash lemma parameter
/// # Errors
/// Returns an error string if R1CS synthesis or proof generation fails.
let prove_evrf_batch
      (sk1:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (my_pk: Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (peers:
          t_Slice
          (u32 & Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config))
      (pads:
          t_Slice
          (u32 &
            Ark_ff.Fields.Models.Fp.t_Fp
              (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                  Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4) &
            Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config))
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
    : Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String =
  let circuit:Golden_dkg.Zk_evrf.Circuit.t_BatchEVRFCircuit =
    Golden_dkg.Zk_evrf.Circuit.impl_BatchEVRFCircuit__new sk1 my_pk peers pads beta
  in
  match
    Golden_dkg.Zk_evrf.Adapter.capture_circuit #Golden_dkg.Zk_evrf.Circuit.t_BatchEVRFCircuit
      circuit
    <:
    Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_CapturedR1CS Alloc.String.t_String
  with
  | Core_models.Result.Result_Ok captured ->
    (match
        Golden_dkg.Zk_evrf.Adapter.to_spartan captured
        <:
        Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_SpartanData Alloc.String.t_String
      with
      | Core_models.Result.Result_Ok spartan_data ->
        let gens:Libspartan.t_NIZKGens
        (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config) =
          Libspartan.impl_4__new #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
              Ark_bls12_381_.Curves.G1.t_Config)
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_cons
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_vars
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_inputs
        in
        let transcript:Merlin.Transcript.t_Transcript =
          Merlin.Transcript.impl_Transcript__new ((let list =
                  [
                    mk_u8 103; mk_u8 111; mk_u8 108; mk_u8 100; mk_u8 101; mk_u8 110; mk_u8 45;
                    mk_u8 101; mk_u8 118; mk_u8 114; mk_u8 102; mk_u8 45; mk_u8 98; mk_u8 97;
                    mk_u8 116; mk_u8 99; mk_u8 104; mk_u8 45; mk_u8 112; mk_u8 114; mk_u8 111;
                    mk_u8 111; mk_u8 102
                  ]
                in
                FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 23);
                Rust_primitives.Hax.array_of_list 23 list)
              <:
              t_Slice u8)
        in
        let
        (tmp0: Merlin.Transcript.t_Transcript),
        (out:
          Libspartan.t_NIZK
          (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config)) =
          Libspartan.impl_5__prove #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
              Ark_bls12_381_.Curves.G1.t_Config)
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_instance
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_vars
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_inputs
            gens
            transcript
        in
        let transcript:Merlin.Transcript.t_Transcript = tmp0 in
        let proof:Libspartan.t_NIZK
        (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config) =
          out
        in
        let proof_bytes:Alloc.Vec.t_Vec u8 Alloc.Alloc.t_Global = Alloc.Vec.impl__new #u8 () in
        (match
            Core_models.Result.impl__map_err #Prims.unit
              #Ark_serialize.Error.t_SerializationError
              #Alloc.String.t_String
              #(Ark_serialize.Error.t_SerializationError -> Alloc.String.t_String)
              (Rust_primitives.Hax.failure "The mutation of this &mut is not allowed here.\n\nThis is discussed in issue https://github.com/hacspec/hax/issues/420.\nPlease upvote or comment this issue if you see this error message.\nNote: the error was labeled with context `DirectAndMut`.\n"
                  "ark_serialize::f_serialize_compressed::<\n &mut alloc::vec::t_Vec<int, alloc::alloc::t_Global>,\n >(&(proof), &mut (proof_bytes))"

                <:
                Core_models.Result.t_Result Prims.unit Ark_serialize.Error.t_SerializationError)
              (fun e ->
                  let e:Ark_serialize.Error.t_SerializationError = e in
                  let args:Ark_serialize.Error.t_SerializationError =
                    e <: Ark_serialize.Error.t_SerializationError
                  in
                  let args:t_Array Core_models.Fmt.Rt.t_Argument (mk_usize 1) =
                    let list =
                      [
                        Core_models.Fmt.Rt.impl__new_display #Ark_serialize.Error.t_SerializationError
                          args
                      ]
                    in
                    FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                    Rust_primitives.Hax.array_of_list 1 list
                  in
                  Core_models.Hint.must_use #Alloc.String.t_String
                    (Alloc.Fmt.format (Core_models.Fmt.Rt.impl_1__new_v1 (mk_usize 1)
                            (mk_usize 1)
                            (let list = ["Failed to serialize proof: "] in
                              FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                              Rust_primitives.Hax.array_of_list 1 list)
                            args
                          <:
                          Core_models.Fmt.t_Arguments)
                      <:
                      Alloc.String.t_String))
            <:
            Core_models.Result.t_Result Prims.unit Alloc.String.t_String
          with
          | Core_models.Result.Result_Ok _ ->
            Core_models.Result.Result_Ok
            ({
                f_proof_bytes = proof_bytes;
                f_num_constraints = spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_cons;
                f_num_vars = spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_vars;
                f_num_inputs = spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_inputs;
                f_is_batch = true
              }
              <:
              t_EVRFProof)
            <:
            Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String
          | Core_models.Result.Result_Err err ->
            Core_models.Result.Result_Err err
            <:
            Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String)
      | Core_models.Result.Result_Err err ->
        Core_models.Result.Result_Err err
        <:
        Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String)
  | Core_models.Result.Result_Err err ->
    Core_models.Result.Result_Err err
    <:
    Core_models.Result.t_Result t_EVRFProof Alloc.String.t_String

/// Verify a single-statement eVRF proof using ark-spartan NIZK.
/// Per Golden paper Section 4.2 (eVRF Verify): verifies the proof `pi`
/// against the public inputs `(PK_1, PK_2, R, beta)`. The verifier re-synthesizes
/// the `R_eVRF` circuit with the claimed public inputs to reconstruct the R1CS
/// instance, then checks the proof against it. This binds the proof to the
/// specific public inputs -- a proof for different inputs will be rejected.
/// # Parameters
/// - `pk1` -- the prover's public key
/// - `pk2` -- the peer's public key (DH counterparty)
/// - `r_commitment` -- the claimed pad commitment `R = g^r`
/// - `beta` -- public leftover hash lemma parameter
/// - `proof` -- the [`EVRFProof`] to verify (must have `is_batch == false`)
/// # Returns
/// `Ok(true)` if the proof verifies, `Ok(false)` if verification fails,
/// or `Err` if deserialization or circuit synthesis fails.
/// # Errors
/// Returns `Err` with a description if the proof is a batch proof (use
/// [`verify_evrf_batch`] instead) or if deserialization fails.
let verify_evrf
      (pk1 pk2 r_commitment:
          Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (proof: t_EVRFProof)
    : Core_models.Result.t_Result bool Alloc.String.t_String =
  if proof.f_is_batch
  then
    Core_models.Result.Result_Err
    (Alloc.String.f_to_string #string
        #FStar.Tactics.Typeclasses.solve
        "Use verify_evrf_batch for batch proofs")
    <:
    Core_models.Result.t_Result bool Alloc.String.t_String
  else
    let circuit:Golden_dkg.Zk_evrf.Circuit.t_EVRFCircuit =
      Golden_dkg.Zk_evrf.Circuit.impl_EVRFCircuit__for_verification pk1 pk2 r_commitment beta
    in
    match
      Golden_dkg.Zk_evrf.Adapter.capture_circuit #Golden_dkg.Zk_evrf.Circuit.t_EVRFCircuit circuit
      <:
      Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_CapturedR1CS Alloc.String.t_String
    with
    | Core_models.Result.Result_Ok captured ->
      (match
          Golden_dkg.Zk_evrf.Adapter.to_spartan captured
          <:
          Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_SpartanData Alloc.String.t_String
        with
        | Core_models.Result.Result_Ok spartan_data ->
          let gens:Libspartan.t_NIZKGens
          (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config) =
            Libspartan.impl_4__new #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
                Ark_bls12_381_.Curves.G1.t_Config)
              spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_cons
              spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_vars
              spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_inputs
          in
          (match
              Core_models.Result.impl__map_err #(Libspartan.t_NIZK
                  (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                    Ark_bls12_381_.Curves.G1.t_Config))
                #Ark_serialize.Error.t_SerializationError
                #Alloc.String.t_String
                #(Ark_serialize.Error.t_SerializationError -> Alloc.String.t_String)
                (Ark_serialize.f_deserialize_compressed #(Libspartan.t_NIZK
                      (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                        Ark_bls12_381_.Curves.G1.t_Config))
                    #FStar.Tactics.Typeclasses.solve
                    #(t_Slice u8)
                    (proof.f_proof_bytes.[ Core_models.Ops.Range.RangeFull
                        <:
                        Core_models.Ops.Range.t_RangeFull ]
                      <:
                      t_Slice u8)
                  <:
                  Core_models.Result.t_Result
                    (Libspartan.t_NIZK
                      (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                        Ark_bls12_381_.Curves.G1.t_Config)) Ark_serialize.Error.t_SerializationError
                )
                (fun e ->
                    let e:Ark_serialize.Error.t_SerializationError = e in
                    let args:Ark_serialize.Error.t_SerializationError =
                      e <: Ark_serialize.Error.t_SerializationError
                    in
                    let args:t_Array Core_models.Fmt.Rt.t_Argument (mk_usize 1) =
                      let list =
                        [
                          Core_models.Fmt.Rt.impl__new_display #Ark_serialize.Error.t_SerializationError
                            args
                        ]
                      in
                      FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                      Rust_primitives.Hax.array_of_list 1 list
                    in
                    Core_models.Hint.must_use #Alloc.String.t_String
                      (Alloc.Fmt.format (Core_models.Fmt.Rt.impl_1__new_v1 (mk_usize 1)
                              (mk_usize 1)
                              (let list = ["Failed to deserialize proof: "] in
                                FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                                Rust_primitives.Hax.array_of_list 1 list)
                              args
                            <:
                            Core_models.Fmt.t_Arguments)
                        <:
                        Alloc.String.t_String))
              <:
              Core_models.Result.t_Result
                (Libspartan.t_NIZK
                  (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                    Ark_bls12_381_.Curves.G1.t_Config)) Alloc.String.t_String
            with
            | Core_models.Result.Result_Ok nizk_proof ->
              let transcript:Merlin.Transcript.t_Transcript =
                Merlin.Transcript.impl_Transcript__new ((let list =
                        [
                          mk_u8 103; mk_u8 111; mk_u8 108; mk_u8 100; mk_u8 101; mk_u8 110; mk_u8 45;
                          mk_u8 101; mk_u8 118; mk_u8 114; mk_u8 102; mk_u8 45; mk_u8 112; mk_u8 114;
                          mk_u8 111; mk_u8 111; mk_u8 102
                        ]
                      in
                      FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 17);
                      Rust_primitives.Hax.array_of_list 17 list)
                    <:
                    t_Slice u8)
              in
              let
              (tmp0: Merlin.Transcript.t_Transcript),
              (out: Core_models.Result.t_Result Prims.unit Libspartan.Errors.t_ProofVerifyError) =
                Libspartan.impl_5__verify #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
                    Ark_bls12_381_.Curves.G1.t_Config)
                  nizk_proof
                  spartan_data.Golden_dkg.Zk_evrf.Adapter.f_instance
                  spartan_data.Golden_dkg.Zk_evrf.Adapter.f_inputs
                  transcript
                  gens
              in
              let transcript:Merlin.Transcript.t_Transcript = tmp0 in
              (match
                  out <: Core_models.Result.t_Result Prims.unit Libspartan.Errors.t_ProofVerifyError
                with
                | Core_models.Result.Result_Ok () ->
                  Core_models.Result.Result_Ok true
                  <:
                  Core_models.Result.t_Result bool Alloc.String.t_String
                | Core_models.Result.Result_Err _ ->
                  Core_models.Result.Result_Ok false
                  <:
                  Core_models.Result.t_Result bool Alloc.String.t_String)
            | Core_models.Result.Result_Err err ->
              Core_models.Result.Result_Err err
              <:
              Core_models.Result.t_Result bool Alloc.String.t_String)
        | Core_models.Result.Result_Err err ->
          Core_models.Result.Result_Err err
          <:
          Core_models.Result.t_Result bool Alloc.String.t_String)
    | Core_models.Result.Result_Err err ->
      Core_models.Result.Result_Err err <: Core_models.Result.t_Result bool Alloc.String.t_String

/// Verify a batched eVRF proof using ark-spartan NIZK with full public-input binding.
/// Per Golden paper Section 5.3: the batch proof covers all `n-1` eVRF evaluations.
/// The verifier re-synthesizes the `BatchEVRFCircuit` with the claimed public inputs
/// (`pk1`, all peer PKs, all `R` commitments, `beta`) to reconstruct the R1CS
/// instance, then checks the proof against it.
/// # Parameters
/// - `pk1` -- the prover's public key
/// - `peers` -- list of `(peer_id, peer_pk)` for all other participants
/// - `pad_commitments` -- list of `(peer_id, R_commitment)` for each peer
/// - `beta` -- public leftover hash lemma parameter
/// - `proof` -- the [`EVRFProof`] to verify (should have `is_batch == true`)
/// # Returns
/// `Ok(true)` if the proof verifies, `Ok(false)` if verification fails,
/// or `Err` if deserialization or circuit synthesis fails.
let verify_evrf_batch
      (pk1: Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config)
      (peers pad_commitments:
          t_Slice
          (u32 & Ark_ec.Models.Short_weierstrass.Affine.t_Affine Ark_bls12_381_.Curves.G1.t_Config))
      (beta:
          Ark_ff.Fields.Models.Fp.t_Fp
            (Ark_ff.Fields.Models.Fp.Montgomery_backend.t_MontBackend
                Ark_bls12_381_.Fields.Fr.t_FrConfig (mk_usize 4)) (mk_usize 4))
      (proof: t_EVRFProof)
    : Core_models.Result.t_Result bool Alloc.String.t_String =
  let circuit:Golden_dkg.Zk_evrf.Circuit.t_BatchEVRFCircuit =
    Golden_dkg.Zk_evrf.Circuit.impl_BatchEVRFCircuit__for_verification pk1
      peers
      pad_commitments
      beta
  in
  match
    Golden_dkg.Zk_evrf.Adapter.capture_circuit #Golden_dkg.Zk_evrf.Circuit.t_BatchEVRFCircuit
      circuit
    <:
    Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_CapturedR1CS Alloc.String.t_String
  with
  | Core_models.Result.Result_Ok captured ->
    (match
        Golden_dkg.Zk_evrf.Adapter.to_spartan captured
        <:
        Core_models.Result.t_Result Golden_dkg.Zk_evrf.Adapter.t_SpartanData Alloc.String.t_String
      with
      | Core_models.Result.Result_Ok spartan_data ->
        let gens:Libspartan.t_NIZKGens
        (Ark_ec.Models.Short_weierstrass.Group.t_Projective Ark_bls12_381_.Curves.G1.t_Config) =
          Libspartan.impl_4__new #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
              Ark_bls12_381_.Curves.G1.t_Config)
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_cons
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_vars
            spartan_data.Golden_dkg.Zk_evrf.Adapter.f_num_inputs
        in
        (match
            Core_models.Result.impl__map_err #(Libspartan.t_NIZK
                (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                  Ark_bls12_381_.Curves.G1.t_Config))
              #Ark_serialize.Error.t_SerializationError
              #Alloc.String.t_String
              #(Ark_serialize.Error.t_SerializationError -> Alloc.String.t_String)
              (Ark_serialize.f_deserialize_compressed #(Libspartan.t_NIZK
                    (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                      Ark_bls12_381_.Curves.G1.t_Config))
                  #FStar.Tactics.Typeclasses.solve
                  #(t_Slice u8)
                  (proof.f_proof_bytes.[ Core_models.Ops.Range.RangeFull
                      <:
                      Core_models.Ops.Range.t_RangeFull ]
                    <:
                    t_Slice u8)
                <:
                Core_models.Result.t_Result
                  (Libspartan.t_NIZK
                    (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                      Ark_bls12_381_.Curves.G1.t_Config)) Ark_serialize.Error.t_SerializationError)
              (fun e ->
                  let e:Ark_serialize.Error.t_SerializationError = e in
                  let args:Ark_serialize.Error.t_SerializationError =
                    e <: Ark_serialize.Error.t_SerializationError
                  in
                  let args:t_Array Core_models.Fmt.Rt.t_Argument (mk_usize 1) =
                    let list =
                      [
                        Core_models.Fmt.Rt.impl__new_display #Ark_serialize.Error.t_SerializationError
                          args
                      ]
                    in
                    FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                    Rust_primitives.Hax.array_of_list 1 list
                  in
                  Core_models.Hint.must_use #Alloc.String.t_String
                    (Alloc.Fmt.format (Core_models.Fmt.Rt.impl_1__new_v1 (mk_usize 1)
                            (mk_usize 1)
                            (let list = ["Failed to deserialize batch proof: "] in
                              FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 1);
                              Rust_primitives.Hax.array_of_list 1 list)
                            args
                          <:
                          Core_models.Fmt.t_Arguments)
                      <:
                      Alloc.String.t_String))
            <:
            Core_models.Result.t_Result
              (Libspartan.t_NIZK
                (Ark_ec.Models.Short_weierstrass.Group.t_Projective
                  Ark_bls12_381_.Curves.G1.t_Config)) Alloc.String.t_String
          with
          | Core_models.Result.Result_Ok nizk_proof ->
            let transcript:Merlin.Transcript.t_Transcript =
              Merlin.Transcript.impl_Transcript__new ((let list =
                      [
                        mk_u8 103; mk_u8 111; mk_u8 108; mk_u8 100; mk_u8 101; mk_u8 110; mk_u8 45;
                        mk_u8 101; mk_u8 118; mk_u8 114; mk_u8 102; mk_u8 45; mk_u8 98; mk_u8 97;
                        mk_u8 116; mk_u8 99; mk_u8 104; mk_u8 45; mk_u8 112; mk_u8 114; mk_u8 111;
                        mk_u8 111; mk_u8 102
                      ]
                    in
                    FStar.Pervasives.assert_norm (Prims.eq2 (List.Tot.length list) 23);
                    Rust_primitives.Hax.array_of_list 23 list)
                  <:
                  t_Slice u8)
            in
            let
            (tmp0: Merlin.Transcript.t_Transcript),
            (out: Core_models.Result.t_Result Prims.unit Libspartan.Errors.t_ProofVerifyError) =
              Libspartan.impl_5__verify #(Ark_ec.Models.Short_weierstrass.Group.t_Projective
                  Ark_bls12_381_.Curves.G1.t_Config)
                nizk_proof
                spartan_data.Golden_dkg.Zk_evrf.Adapter.f_instance
                spartan_data.Golden_dkg.Zk_evrf.Adapter.f_inputs
                transcript
                gens
            in
            let transcript:Merlin.Transcript.t_Transcript = tmp0 in
            (match
                out <: Core_models.Result.t_Result Prims.unit Libspartan.Errors.t_ProofVerifyError
              with
              | Core_models.Result.Result_Ok () ->
                Core_models.Result.Result_Ok true
                <:
                Core_models.Result.t_Result bool Alloc.String.t_String
              | Core_models.Result.Result_Err _ ->
                Core_models.Result.Result_Ok false
                <:
                Core_models.Result.t_Result bool Alloc.String.t_String)
          | Core_models.Result.Result_Err err ->
            Core_models.Result.Result_Err err
            <:
            Core_models.Result.t_Result bool Alloc.String.t_String)
      | Core_models.Result.Result_Err err ->
        Core_models.Result.Result_Err err <: Core_models.Result.t_Result bool Alloc.String.t_String)
  | Core_models.Result.Result_Err err ->
    Core_models.Result.Result_Err err <: Core_models.Result.t_Result bool Alloc.String.t_String
