module Golden_dkg.FnOnce_instances

/// FnOnce instances for closure types generated by hax extraction.
///
/// hax generates closures with dependent types that F*'s typeclass
/// resolver can't always unify with simple function types.
/// We provide a blanket instance that works for any function-like type.

open Core_models.Ops.Function

/// FnOnce for 2-arg functions with dependent binders.
/// hax extraction generates `_: A -> _: B -> C` (dependent) rather than
/// `A -> B -> C` (non-dependent). This instance matches the dependent form.
unfold instance fnonce_dep_arrow_2 (t1 t2 u: Type0)
  : t_FnOnce (_:t1 -> _:t2 -> u) (t1 & t2) = {
    f_Output = u;
    f_call_once_pre = (fun _ _ -> true);
    f_call_once_post = (fun _ _ _ -> true);
    f_call_once = (fun f args -> f args._1 args._2);
  }

/// Blanket Fn instance for higher-order function parameters.
/// Uses admit() -- in --lax mode the False precondition is dismissed.
[@@ FStar.Tactics.Typeclasses.tcinstance]
let impl_fn_blanket (#v_F: Type0) (#v_Args: Type0) : t_Fn v_F v_Args = admit ()
