module Golden_rs.FnOnce_instances

/// FnOnce instances for dependent closure types generated by hax extraction.
///
/// hax generates closures with dependent types like:
///   _ : a -> _ : (fun _ -> b) _ -> (fun _ _ -> c) _ _
/// These don't reduce to `a -> b -> c` during typeclass resolution.
/// We provide explicit instances matching the dependent form.

open Core_models.Ops.Function

/// Blanket FnOnce for any 2-arg function where the return type
/// is independent of the arguments (most common case in golden-rs).
/// This matches both the simple `a -> b -> c` and the dependent
/// `a -> (fun _ -> b) _ -> (fun _ _ -> c) _ _` forms because
/// F* unifies them at the type level.
[@@ FStar.Tactics.Typeclasses.tcinstance]
let impl_fnonce_fold_closure (#v_Acc #v_Item: Type0)
  : t_FnOnce (v_Acc -> v_Item -> v_Acc) (v_Acc & v_Item) =
  {
    f_Output = v_Acc;
    f_call_once_pre = (fun _ _ -> true);
    f_call_once_post = (fun _ _ _ -> true);
    f_call_once = (fun f args -> f args._1 args._2);
  }
