//! Zero-knowledge eVRF proof system per Section 4 of the Golden paper.
//!
//! Proves the R_eVRF relation from Figure 3 of the Golden paper (IACR 2025/1924):
//! the prover demonstrates that an eVRF pad was correctly derived from a DH shared
//! secret without revealing the secret key. The circuit captures the R_eVRF relation
//! (Section 4.3) and produces an ark-spartan NIZK proof over BLS12-381 G1.
//!
//! Per Section 5.3/4.6, batch optimization allows proving `n-1` eVRF evaluations
//! in a single proof by sharing the `sk_1` bit-decomposition across all statements.

pub mod adapter;
pub mod bit_decompose;
pub mod circuit;
pub mod exponentiation;
pub mod nonnative;

use ark_bls12_381::{Fr, G1Affine, G1Projective};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use borsh::{BorshDeserialize, BorshSerialize};
use std::io::{self, Read, Write};

use self::adapter::capture_circuit;
use self::circuit::{BatchEVRFCircuit, EVRFCircuit};
use crate::types::NodeId;
use libspartan::{NIZKGens, NIZK};

/// An eVRF proof using ark-spartan's NIZK proof system.
///
/// Per Golden paper Section 3.4: "We use Bulletproofs [15] to prove R1CS satisfiability."
/// The proof is generated by ark-spartan's NIZK system which provides a production-quality
/// R1CS-to-IPA reduction with correct public-input binding.
#[derive(Clone, Debug)]
pub struct EVRFProof {
    /// Serialized ark-spartan NIZK proof (CanonicalSerialize compressed bytes).
    pub proof_bytes: Vec<u8>,
    /// Number of R1CS constraints.
    pub num_constraints: usize,
    /// Number of witness variables.
    pub num_vars: usize,
    /// Number of public inputs.
    pub num_inputs: usize,
    /// Whether this is a batch proof (Section 5.3).
    pub is_batch: bool,
}

impl BorshSerialize for EVRFProof {
    fn serialize<W: Write>(&self, writer: &mut W) -> io::Result<()> {
        BorshSerialize::serialize(&(self.num_constraints as u32), writer)?;
        BorshSerialize::serialize(&(self.num_vars as u32), writer)?;
        BorshSerialize::serialize(&(self.num_inputs as u32), writer)?;
        BorshSerialize::serialize(&self.is_batch, writer)?;
        BorshSerialize::serialize(&self.proof_bytes, writer)?;
        Ok(())
    }
}

impl BorshDeserialize for EVRFProof {
    fn deserialize_reader<R: Read>(reader: &mut R) -> io::Result<Self> {
        let num_constraints = u32::deserialize_reader(reader)? as usize;
        let num_vars = u32::deserialize_reader(reader)? as usize;
        let num_inputs = u32::deserialize_reader(reader)? as usize;
        let is_batch: bool = BorshDeserialize::deserialize_reader(reader)?;
        let proof_bytes: Vec<u8> = BorshDeserialize::deserialize_reader(reader)?;
        Ok(EVRFProof {
            proof_bytes,
            num_constraints,
            num_vars,
            num_inputs,
            is_batch,
        })
    }
}

/// Generate an eVRF proof for a single statement using ark-spartan NIZK.
///
/// Per Golden paper Section 4.2 (eVRF Evaluate): produces a ZK proof `pi`
/// for the R_eVRF relation (Figure 3) that the eVRF pad was correctly derived.
pub fn prove_evrf(
    sk1: Fr,
    pk1: G1Affine,
    pk2: G1Affine,
    r_value: Fr,
    r_commitment: G1Affine,
    beta: Fr,
) -> Result<EVRFProof, String> {
    let circuit = EVRFCircuit::new(sk1, pk1, pk2, r_value, r_commitment, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    let mut transcript = merlin::Transcript::new(b"golden-evrf-proof");
    let proof = NIZK::prove(
        &spartan_data.instance,
        spartan_data.vars,
        &spartan_data.inputs,
        &gens,
        &mut transcript,
    );

    // Serialize the proof
    let mut proof_bytes = Vec::new();
    proof
        .serialize_compressed(&mut proof_bytes)
        .map_err(|e| format!("Failed to serialize proof: {}", e))?;

    Ok(EVRFProof {
        proof_bytes,
        num_constraints: spartan_data.num_cons,
        num_vars: spartan_data.num_vars,
        num_inputs: spartan_data.num_inputs,
        is_batch: false,
    })
}

/// Generate a batched eVRF proof for all peers using ark-spartan NIZK.
///
/// Per Golden paper Section 5.3/4.6: one proof covers all n-1 eVRF evaluations.
pub fn prove_evrf_batch(
    sk1: Fr,
    my_pk: G1Affine,
    peers: &[(NodeId, G1Affine)],
    pads: &[(NodeId, Fr, G1Affine)],
    beta: Fr,
) -> Result<EVRFProof, String> {
    let circuit = BatchEVRFCircuit::new(sk1, my_pk, peers, pads, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    let mut transcript = merlin::Transcript::new(b"golden-evrf-batch-proof");
    let proof = NIZK::prove(
        &spartan_data.instance,
        spartan_data.vars,
        &spartan_data.inputs,
        &gens,
        &mut transcript,
    );

    let mut proof_bytes = Vec::new();
    proof
        .serialize_compressed(&mut proof_bytes)
        .map_err(|e| format!("Failed to serialize proof: {}", e))?;

    Ok(EVRFProof {
        proof_bytes,
        num_constraints: spartan_data.num_cons,
        num_vars: spartan_data.num_vars,
        num_inputs: spartan_data.num_inputs,
        is_batch: true,
    })
}

/// Verify an eVRF proof using ark-spartan NIZK.
///
/// Per Golden paper Section 4.2 (eVRF Verify): verifies the proof `pi`
/// against the public inputs (PK_1, PK_2, R, beta). The verifier re-synthesizes
/// the R_eVRF circuit with the claimed public inputs to reconstruct the R1CS
/// instance, then checks the proof against it. This binds the proof to the
/// specific public inputs -- a proof for different inputs will be rejected.
pub fn verify_evrf(
    pk1: G1Affine,
    pk2: G1Affine,
    r_commitment: G1Affine,
    beta: Fr,
    proof: &EVRFProof,
) -> Result<bool, String> {
    if proof.is_batch {
        return Err("Use verify_evrf_batch for batch proofs".to_string());
    }

    // 1. Re-synthesize the circuit with the verifier's public inputs
    let circuit = EVRFCircuit::for_verification(pk1, pk2, r_commitment, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    // 2. Reconstruct generators
    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    // 3. Deserialize the proof
    let nizk_proof = NIZK::<G1Projective>::deserialize_compressed(&proof.proof_bytes[..])
        .map_err(|e| format!("Failed to deserialize proof: {}", e))?;

    // 4. Verify with the verifier's public inputs
    let mut transcript = merlin::Transcript::new(b"golden-evrf-proof");
    match nizk_proof.verify(
        &spartan_data.instance,
        &spartan_data.inputs,
        &mut transcript,
        &gens,
    ) {
        Ok(()) => Ok(true),
        Err(_) => Ok(false),
    }
}

/// Verify a batched eVRF proof using ark-spartan NIZK with full public-input binding.
///
/// Per Golden paper Section 5.3: the batch proof covers all n-1 eVRF evaluations.
/// The verifier re-synthesizes the BatchEVRFCircuit with the claimed public inputs
/// (pk1, all peer PKs, all R commitments, beta) to reconstruct the R1CS instance,
/// then checks the proof against it.
pub fn verify_evrf_batch(
    pk1: G1Affine,
    peers: &[(NodeId, G1Affine)],
    pad_commitments: &[(NodeId, G1Affine)],
    beta: Fr,
    proof: &EVRFProof,
) -> Result<bool, String> {
    // Re-synthesize the batch circuit with the verifier's public inputs
    let circuit = BatchEVRFCircuit::for_verification(pk1, peers, pad_commitments, beta);
    let captured = capture_circuit(circuit)?;
    let spartan_data = self::adapter::to_spartan(&captured)?;

    // Reconstruct generators
    let gens = NIZKGens::<G1Projective>::new(
        spartan_data.num_cons,
        spartan_data.num_vars,
        spartan_data.num_inputs,
    );

    // Deserialize the proof
    let nizk_proof = NIZK::<G1Projective>::deserialize_compressed(&proof.proof_bytes[..])
        .map_err(|e| format!("Failed to deserialize batch proof: {}", e))?;

    // Verify with the verifier's public inputs
    let mut transcript = merlin::Transcript::new(b"golden-evrf-batch-proof");
    match nizk_proof.verify(
        &spartan_data.instance,
        &spartan_data.inputs,
        &mut transcript,
        &gens,
    ) {
        Ok(()) => Ok(true),
        Err(_) => Ok(false),
    }
}

#[cfg(test)]
mod verification_tests {
    use super::*;
    use ark_ec::{AffineRepr, CurveGroup};
    use ark_ff::UniformRand;

    #[test]
    fn test_verify_evrf_valid_proof() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let sk2 = Fr::rand(&mut rng);
        let pk2 = (G1Affine::generator() * sk2).into_affine();
        let r_value = Fr::rand(&mut rng);
        let r_commitment = (G1Affine::generator() * r_value).into_affine();
        let beta = Fr::rand(&mut rng);

        let proof = prove_evrf(sk1, pk1, pk2, r_value, r_commitment, beta).unwrap();
        let result = verify_evrf(pk1, pk2, r_commitment, beta, &proof).unwrap();
        assert!(result, "Valid proof should verify");
    }

    #[test]
    fn test_verify_evrf_wrong_public_inputs() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let sk2 = Fr::rand(&mut rng);
        let pk2 = (G1Affine::generator() * sk2).into_affine();
        let r_value = Fr::rand(&mut rng);
        let r_commitment = (G1Affine::generator() * r_value).into_affine();
        let beta = Fr::rand(&mut rng);

        let proof = prove_evrf(sk1, pk1, pk2, r_value, r_commitment, beta).unwrap();

        // Verify with WRONG pk2 -- should fail
        let wrong_pk2 = (G1Affine::generator() * Fr::rand(&mut rng)).into_affine();
        let result = verify_evrf(pk1, wrong_pk2, r_commitment, beta, &proof).unwrap();
        assert!(
            !result,
            "Proof verified against wrong public inputs should fail"
        );
    }

    #[test]
    fn test_verify_evrf_batch_valid() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let beta = Fr::rand(&mut rng);

        // Create 3 peers
        let mut peers = Vec::new();
        let mut pads = Vec::new();
        let mut pad_commitments = Vec::new();
        for peer_id in 2..=4u32 {
            let sk_peer = Fr::rand(&mut rng);
            let pk_peer = (G1Affine::generator() * sk_peer).into_affine();
            let r_value = Fr::rand(&mut rng);
            let r_commitment = (G1Affine::generator() * r_value).into_affine();
            peers.push((peer_id, pk_peer));
            pads.push((peer_id, r_value, r_commitment));
            pad_commitments.push((peer_id, r_commitment));
        }

        let proof = prove_evrf_batch(sk1, pk1, &peers, &pads, beta).unwrap();

        // Verify with correct public inputs
        let result = verify_evrf_batch(pk1, &peers, &pad_commitments, beta, &proof).unwrap();
        assert!(result, "Valid batch proof should verify");
    }

    #[test]
    fn test_verify_evrf_batch_wrong_peer() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let beta = Fr::rand(&mut rng);

        let mut peers = Vec::new();
        let mut pads = Vec::new();
        let mut pad_commitments = Vec::new();
        for peer_id in 2..=4u32 {
            let sk_peer = Fr::rand(&mut rng);
            let pk_peer = (G1Affine::generator() * sk_peer).into_affine();
            let r_value = Fr::rand(&mut rng);
            let r_commitment = (G1Affine::generator() * r_value).into_affine();
            peers.push((peer_id, pk_peer));
            pads.push((peer_id, r_value, r_commitment));
            pad_commitments.push((peer_id, r_commitment));
        }

        let proof = prove_evrf_batch(sk1, pk1, &peers, &pads, beta).unwrap();

        // Verify with WRONG peer PK -- should fail
        let mut wrong_peers = peers.clone();
        wrong_peers[1].1 = (G1Affine::generator() * Fr::rand(&mut rng)).into_affine();
        let result = verify_evrf_batch(pk1, &wrong_peers, &pad_commitments, beta, &proof).unwrap();
        assert!(!result, "Batch proof with wrong peer PK should fail");
    }

    #[test]
    fn test_verify_evrf_wrong_beta() {
        let mut rng = ark_std::test_rng();
        let sk1 = Fr::rand(&mut rng);
        let pk1 = (G1Affine::generator() * sk1).into_affine();
        let sk2 = Fr::rand(&mut rng);
        let pk2 = (G1Affine::generator() * sk2).into_affine();
        let r_value = Fr::rand(&mut rng);
        let r_commitment = (G1Affine::generator() * r_value).into_affine();
        let beta = Fr::rand(&mut rng);

        let proof = prove_evrf(sk1, pk1, pk2, r_value, r_commitment, beta).unwrap();

        // Verify with WRONG beta -- should fail
        let wrong_beta = Fr::rand(&mut rng);
        let result = verify_evrf(pk1, pk2, r_commitment, wrong_beta, &proof).unwrap();
        assert!(!result, "Proof verified against wrong beta should fail");
    }
}
