

# This file was *autogenerated* from the file /wrk/tmt/goldenkeysharing/scripts/find_gout_curve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab = Integer(0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_10000 = Integer(10000); _sage_const_1 = Integer(1); _sage_const_100 = Integer(100); _sage_const_60 = Integer(60); _sage_const_101 = Integer(101); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_1000 = Integer(1000); _sage_const_20 = Integer(20)#!/usr/bin/env sage

# Target: find E/F_{q'} with #E = p where p = Fq(BLS12-381)
p = _sage_const_0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab 

print(f"Target order p = {p}")
print(f"p is prime: {is_prime(p)}")
print(f"p bit length: {p.nbits()}")

# Search: for small traces t, compute q' = p + t - 1, check if q' is prime,
# then check if a simple curve y^2 = x^3 + b over F_{q'} has order p.
#
# #E(F_{q'}) = q' + 1 - trace => q' = p + trace - 1
#
# We try both positive and negative traces starting from small |t|.
# For each prime q', we try y^2 = x^3 + b for small b.

import sys

found = False
curves_checked = _sage_const_0 

for t in range(_sage_const_2 , _sage_const_10000 ):
    for sign in [_sage_const_1 , -_sage_const_1 ]:
        trace = sign * t
        q_prime = p + trace - _sage_const_1 
        if q_prime < _sage_const_2 :
            continue
        if not is_prime(q_prime):
            continue

        print(f"  Trying trace={trace}, q' is prime, checking curves...", flush=True)

        F = GF(q_prime)
        # Try y^2 = x^3 + b (a=0) for small b
        for b in range(_sage_const_1 , _sage_const_100 ):
            try:
                E = EllipticCurve(F, [_sage_const_0 , b])
                curves_checked += _sage_const_1 
                order = E.order()
                if order == p:
                    print(f"\n{'='*_sage_const_60 }")
                    print(f"FOUND!")
                    print(f"{'='*_sage_const_60 }")
                    print(f"  trace t = {trace}")
                    print(f"  q' = {q_prime}")
                    print(f"  q' hex = {hex(q_prime)}")
                    print(f"  q' bit length = {q_prime.nbits()}")
                    print(f"  curve: y^2 = x^3 + {b} over F_{{q'}}")
                    print(f"  #E = {order}")
                    print(f"  #E == p: {order == p}")

                    # Find a generator (since order is prime, any non-identity point generates)
                    G = E.random_point()
                    while G == E(_sage_const_0 ):
                        G = E.random_point()

                    print(f"  Generator G:")
                    print(f"    x = {hex(int(G[_sage_const_0 ]))}")
                    print(f"    y = {hex(int(G[_sage_const_1 ]))}")

                    # Verify order
                    assert p * G == E(_sage_const_0 ), "Order check failed!"
                    assert (p - _sage_const_1 ) * G != E(_sage_const_0 ), "Order too small!"
                    print(f"  Order verification: PASSED")

                    # Security checks
                    print(f"\n  Security checks:")
                    print(f"  q' != p (not anomalous): {q_prime != p}")
                    emb_deg = None
                    for k in range(_sage_const_1 , _sage_const_101 ):
                        if pow(int(q_prime), k, int(p)) == _sage_const_1 :
                            emb_deg = k
                            print(f"    Embedding degree k = {k}")
                            break
                    if emb_deg is None:
                        print(f"    No small embedding degree (checked k=1..100): GOOD")

                    disc = trace * trace - _sage_const_4  * q_prime
                    print(f"  CM discriminant D = {disc}")

                    print(f"\n  Curves checked total: {curves_checked}")
                    found = True
                    break
                else:
                    # Print progress occasionally
                    if curves_checked % _sage_const_5  == _sage_const_0 :
                        print(f"    b={b}: order mismatch (curves checked: {curves_checked})", flush=True)
            except Exception as e:
                continue
        if found:
            break
    if found:
        break

if not found:
    print(f"\nNo curve found with y^2 = x^3 + b. Curves checked: {curves_checked}")
    print("Trying y^2 = x^3 + ax + b ...")
    for t in range(_sage_const_2 , _sage_const_1000 ):
        for sign in [_sage_const_1 , -_sage_const_1 ]:
            trace = sign * t
            q_prime = p + trace - _sage_const_1 
            if q_prime < _sage_const_2  or not is_prime(q_prime):
                continue
            print(f"  Trying trace={trace}, q' is prime, checking curves...", flush=True)
            F = GF(q_prime)
            for a in range(_sage_const_1 , _sage_const_20 ):
                for b in range(_sage_const_1 , _sage_const_20 ):
                    try:
                        E = EllipticCurve(F, [a, b])
                        curves_checked += _sage_const_1 
                        if E.order() == p:
                            print(f"\n{'='*_sage_const_60 }")
                            print(f"FOUND!")
                            print(f"{'='*_sage_const_60 }")
                            print(f"  trace t = {trace}")
                            print(f"  q' = {hex(q_prime)}")
                            print(f"  curve: y^2 = x^3 + {a}x + {b} over F_{{q'}}")
                            G = E.random_point()
                            while G == E(_sage_const_0 ):
                                G = E.random_point()
                            print(f"  Generator G:")
                            print(f"    x = {hex(int(G[_sage_const_0 ]))}")
                            print(f"    y = {hex(int(G[_sage_const_1 ]))}")
                            assert p * G == E(_sage_const_0 )
                            assert (p - _sage_const_1 ) * G != E(_sage_const_0 )
                            print(f"  Order verified!")
                            print(f"  q' != p: {q_prime != p}")
                            found = True
                            break
                    except:
                        continue
                if found:
                    break
            if found:
                break
        if found:
            break

if not found:
    print(f"\nNo curve found in search range. Total curves checked: {curves_checked}")

